### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by takenek** [knrd1/chatgpt#4] opened 2023-03-20 14:23 UTC
I just run a bot and it's crash.
Please add handling for error:

root@radvd:~/chatgpt# ./chatgpt.py
Traceback (most recent call last):
  File "/root/chatgpt/./chatgpt.py", line 25, in <module>
    message = irc.recv(2048).decode("UTF-8")
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by takenek** [comment] 2023-03-21 09:56
Hey
Problem still exist i just pull new version and get same error but other line:

root@radvd:~/chatgpt# python3 chatgpt.py
Traceback (most recent call last):
  File "/root/chatgpt/chatgpt.py", line 28, in <module>
    message = irc.recv(2048).decode("UTF-8")
ConnectionResetError: [Errno 104] Connection reset by peer


Best Regards
TaKeN

**Comment by takenek** [comment] 2023-03-22 05:00
And problem still exist:

root@radvd:~/chatgpt# python3 chatgpt.py
connecting to:irc.wroclaw.pl
connected to:irc.wroclaw.pl
Traceback (most recent call last):
  File "/root/chatgpt/chatgpt.py", line 37, in <module>
    message = irc.recv(2048).decode("UTF-8")
ConnectionResetError: [Errno 104] Connection reset by peer
root@radvd:~/chatgpt#

**Comment by knrd1** [comment] 2023-03-22 18:34
As discussed, I'm unable to reproduce this error. 

Looks like certain conditions must be met to get this error, e.g: port 113 is blocked using DROP rule (Not REJECT). 

Also, it's intermittent, doesn't happen always, even if the condition is met. 

Closing, this won't be "fixed".

**Closed by knrd1** 2023-03-22 18:34 UTC
Labels: bug
